# 基础设置，需将music_directory后的路径改为你自己的音乐目录的绝对路径
music_directory	    "/home/l/nvmeE/nas备份/music"   # 在这个文件夹中扫描音乐
db_file             "~/.config/mpd/database"        # 音乐数据库
log_file            "~/.config/mpd/log"             # 日志
playlist_directory  "~/.config/mpd/playlists"       # 播放列表存储文件夹
pid_file            "~/.config/mpd/pid"             # MPD 存储进程 ID（PID）的文件
state_file          "~/.config/mpd/state"           # 记录 MPD 当前状态
sticker_file        "~/.config/mpd/sticker.sql"     # 标签数据库
bind_to_address		"localhost"
port				"6600"

# 在音乐目录下的文件变动时自动刷新数据库
auto_update             "yes"
restore_paused          "yes"
auto_update_depth       "4"


# alsa输出的配置音频
#audio_output {
#	type		    "alsa"
#	name		    "ALSA"
#	device		    "hw:0,0"	# optional
#	mixer_type      "hardware"	# optional
#	mixer_device	"default"	# optional
#	mixer_control	"Master"	# optional
#	mixer_index	    "0"		    # optional
#}

# PipeWire 输出可以配置,（蓝牙耳机使用的pipewire-pulse）
audio_output {
       type            "pipewire"
       name            "PipeWire Sound Server"
}

# 配置可视化界面
audio_output {
       type	"fifo"
       name	"Visualizer feed"
       path	"/tmp/mpd.fifo"
       format	"44100:16:2"
}


